### ISSUE TITLE
Proposal for BiMLPA integration in CDlib 

### ISSUE THREAD

**Issue by GiulioRossetti** [marblet/BiMLPA#1]
Hi,
I've found your algorithm by searching CD approaches in GitHub. 
I'm one of the authors of [CDlib](https://github.com/GiulioRossetti/cdlib) a python library that provides standardized access to several community discovery algorithms (~40 in its last release) along with evaluation measures and plotting facilities. 

We are constantly searching for new algorithms to add to our collection: would you like your BiMLPA to be included in CDlib? If so, let me know: we can easily take care of everything.

Best,
Giulio

**Comment by hbkt** [comment]
Thank you for suggesting me such a wonderful thing.
Your project CDlib seems interesting.

I would love to include my algorithm BiMLPA in your library.
Thank you.

**Comment by GiulioRossetti** [comment]
That's great!

Would you mind if I prepare a pull request that will allow you to generate a python package and upload it on pypi?

This way it will be easier to: 1) add BiMLPA in cdlib; 2) maintain your version and the cdlib one in sync in case of code update.

Best,
Giulio

**Comment by GiulioRossetti** [comment]
I've made the pull request (#2  ) to simplify the integration.

**Comment by hbkt** [comment]
I uploaded the package to PyPI.
https://pypi.org/project/bimlpa/

**Comment by GiulioRossetti** [comment]
Integration in CDlib completed.
